PUT http://localhost:8080/events/2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiZXhwIjoxNzMxNjEzODQ3LCJ1c2VySWQiOjF9.ur5Sbzo-zVCUGu4_6byZGOc8pMhXXN8RQnRFUJC66PI

{
    "name": "updated test event",
    "description": "a test event updated",
    "location": "test location USA",
    "dateTime": "2025-01-01T15:30:00Z"
}